easy_admin:
    site_name: "<img src='images/logo.png' alt='logo' class='logo'> Donutopia Admin"
    user:
        display_name: true
        name_property_path: "firstName"
    entities:
        # Entities to manage in admin dashboard
        Product:
            class: App\Entity\Product
            label: "Product"
            list:

            form:
              fields:
                - {type: "group", icon: "pencil", label: "Basic Information", css_class: "col-lg-7"}
                - name
                - {property: "description", type: "text-editor"}
                - {type: "group", label: "details", css_class: "col-lg-5"}
                - category
                - price
                - images



        Category:
            class: App\Entity\Category
        User:
            class: App\Entity\User
        Price:
            class: App\Entity\Price
        Order:
            class: App\Entity\Order
        Images:
            class: App\Entity\Images


    list:
        actions:
            - {name: 'show', icon: 'eye', label: ''}
            - {name: 'edit', icon: 'pen', label: ''}
            - {name: 'delete', icon: 'trash-alt', label: ''}
            - {name: 'new', icon: 'plus-circle', label: ''}

    design:
        assets:
            css:
                - '/css/dashboard.css'
            favicon: "/images/Donutopia2-kopie.png"


        menu:
            - {label: "Home"}

            - {label: "Shop"}
            - label: "Producten"
              icon: "tag"
              children:
                - {entity: Product, label: "Producten", icon: "list"}
                - {entity: Product, label: "Toevoegen", params:{action: "new"}, icon: "plus"}
            - label: "Categoriën"
              icon: "layer-group"
              children:
                - {entity: Category, label: "Categoriën", icon: "list"}
                - {entity: Category, label: "Toevoegen", icon: "plus"}
            - label: Afbeeldingen
            - {entity: Images, label: "Afbeeldingen", icon: "image"}
            - {label: "Bestellingen"}
            - {entity: Order, label: "Bestellingen", icon: "shopping-basket"}
            - {label: "Gebruikers"}
            - {entity: User, icon: "user", label: "Gebruikers"}





