easy_admin:
    site_name: " Donutopia Admin"
#  <img src='/images/logo.png' alt='logo' class='logo'>
    user:
        display_name: true
        name_property_path: "firstName"

    design:
      assets:
        css:
          - '/css/dashboard.css'
        favicon: "/images/logo.png"

      menu:
        - {label: "Shop"}
        - label: "Producten"
          icon: "tag"
          children:
            - {entity: Product, label: "Producten", icon: "list"}
            - {entity: Product, label: "Toevoegen", params:{action: "new"}, icon: "plus"}
        - label: "Categoriën"
          icon: "layer-group"
          children:
            - {entity: Category, label: "Categoriën", icon: "list"}
            - {entity: Category, label: "Toevoegen", params: {action: "new"}, icon: "plus"}
        - label: Afbeeldingen
        - {entity: Images, label: "Afbeeldingen", icon: "image"}
        - {label: "Bestellingen"}
        - {entity: Order, label: "Bestellingen", icon: "shopping-basket"}
        - {label: "Gebruikers"}
        - {entity: User, icon: "user", label: "Gebruikers"}

    entities:
        # Entities to manage in admin dashboard
        Product:
            class: App\Entity\Product
            label: "Product"
            show:
              fields:
#                - {type: "group", icon: "pencil", label: "Informatie", css_class: "col-lg-7"}
                - name
                - {property: "description", type: "raw"}
                - category
                - price
                - createdAt
                - updatedAt
#                - {type: "group", label: "Afbeeldingen", css_class: "col-lg-5"}
                - {property: "images", template: "images.html.twig", type_options: {entry_type: 'App\Form\ImagesType', by_reference: false} }

            form:
              fields:
                - {type: "group", icon: "pencil", label: "Informatie", css_class: "col-lg-7"}
                - name
                - {property: "description", type: "text-editor"}
                - {type: "group", label: "Details", css_class: "col-lg-5"}
                - category
                - price
                - {type: "group", label: "Upload afbeeldingen", css_class: "col-lg-5" }
                - {property: "images", type: "collection", type_options: {entry_type: 'App\Form\ImagesType', by_reference: false} }
            list:
              fields:
                - id
                - name
                - description
                - images
                - {property: "category", }



        Category:
            class: App\Entity\Category
            list:
              fields:
                - id
                - name
                - description
                - {property: "img", type: "image", base_path: "%uploads_categories_path%"}

            form:
              fields:
                - {type: "group", label: "Informatie", css_class: "col-lg-7"}
                - name
                - {property: "description", type: "text-editor"}
                - {type: "group", label: "Upload afbeelding", css_class: "col-lg-5", icon: "clip"}
                - {property: "imgFile", type: "vich_image"}
            show:
              fields:
#                - {type: "group", label: "Informatie", css_class: "col-lg-7"}
                - name
                - {property: "description", type: "raw"}
                - createdAt
                - updatedAt
#                - {type: "group", label: "Afbeelding", css_class: "col-lg-5"}
                - {property: "img", type: "image", base_path: "%uploads_categories_path%"}

        Images:
          class: App\Entity\Images
          disabled_actions: ["edit"]
          list:
            fields:
              - id
              - {property: "image", type: "image", base_path: "%uploads_products_path%"}
              - imageAlt
          show:
            fields:
              - {property: "imageAlt", label: "Name"}
              - {property: "image", type: "image", base_path: "%uploads_products_path%"}
              - {property: "product"}



        Order:
          class: App\Entity\Order
          disabled_actions: ["new", "edit"]

        User:
            class: App\Entity\User
            disabled_actions: ["new", "edit"]
            list:
              fields:
                - id
                - firstName
                - lastname
                - email
                - phone
                - roles
            show:
              fields:
                - firstname
                - lastname
                - email
                - phone
                - address
                - {property: "postalCode", type_options: {disabled: true}}
                - createdAt
                - updatedAt




    list:
        actions:
            - {name: 'show', icon: 'eye', label: ''}
            - {name: 'edit', icon: 'pen', label: ''}
            - {name: 'delete', icon: 'trash-alt', label: ''}
            - {name: 'new', icon: 'plus-circle', label: ''}







