easy_admin:
    site_name: " <img src='./images/logo.png' alt='logo' class='logo'>  Donutopia Admin"
    user:
        display_name: true
        name_property_path: "firstName"
    formats:
      date:     'd/m/Y'
      time:     'H:i'
      datetime: 'd/m/Y H:i:s'

    list:
      actions:
        - {name: 'show', icon: 'eye', label: ''}
        - {name: 'edit', icon: 'pen', label: ''}
        - {name: 'delete', icon: 'trash-alt', label: ''}
        - {name: 'new', icon: 'plus-circle', label: ''}

    design:
      assets:
        css:
          - 'css/dashboard.css'
        favicon: "images/logo.png"
      menu:
        - {label: "Shop"}
        - label: "Producten"
          icon: "tag"
          children:
            - {entity: Product, label: "Producten", icon: "list"}
            - {entity: Product, label: "Product toevoegen", params:{action: "new"}, icon: "plus"}
        - label: "Prijzen"
          icon: "euro"
          children:
            - {entity: Price, label: "Prijzen", icon: "list"}
            - {entity: Price, label: "Prijs toevoegen", icon: "plus", params:{action: "new"}}
        - label: "Categoriën"
          icon: "layer-group"
          children:
            - {entity: Category, label: "Categoriën", icon: "list"}
            - {entity: Category, label: "Toevoegen", params: {action: "new"}, icon: "plus"}
        - label: Afbeeldingen
        - {entity: Images, label: "Afbeeldingen", icon: "image"}
        - {label: "Bestellingen"}
        - {entity: Orders, label: "Bestellingen", icon: "shopping-basket"}
        - {label: "Gebruikers"}
        - {entity: User, icon: "user", label: "Gebruikers"}

    entities:
        # Entities to manage in admin dashboard
        Product:
            class: App\Entity\Product
            label: "Producten"
            help: "Bekijk, wijzig, creëer en verwijder producten."
            show:
              help:
              fields:
#                - {type: "group", icon: "pencil", label: "Informatie", css_class: "col-lg-7"}
                - {property: "name", label: "Naam"}
                - {property: "description", type: "raw", label: "Omschrijving"}
                - {property: "category", label: "Categorie"}
                - {property: "price",  label: "Prijs"}
                - {property: "createdAt", label: "Gecreëerd"}
                - {property: "updatedAt", label: "Geüpdatet"}
#                - {type: "group", label: "Afbeeldingen", css_class: "col-lg-5"}
                - {property: "images", template: "images.html.twig", type_options: {entry_type: 'App\Form\ImagesType', by_reference: false}, label: "Afbeeldingen" }

            form:
              title: "Product toevoegen"
              help:
              fields:
                - {type: "group", label: "Informatie", css_class: "col-lg-7"}
                - {property: "name", label: "Naam"}
                - {property: "description", type: "text-editor", label: "Omschrijving"}
                - {type: "group", label: "Details", css_class: "col-lg-5"}
                - {property: "category", label: "Categorie", type: "easyadmin_autocomplete"}
#                - {property: "price",  type: "collection", type_options: { entry_type: 'App\Form\PriceType', by_reference: false }, label: "Pris"}
                - {property: "price",  label: "Prijs"}
                - {type: "group", label: "Upload afbeeldingen", css_class: "col-lg-5" }
                - {property: "images", type: "collection", type_options: {entry_type: 'App\Form\ImagesType', by_reference: false}, label: "Afbeeldingen" }
            list:
              fields:
                - id
                - {property: "name", label: "Naam"}
                - {property: "description", type: "raw", label: "Omschrijving"}
                - {property: "images", label: "Afbeeldingen"}
                - {property: "category", label: "Categorie" }



        Category:
            class: App\Entity\Category
            label: "Categoriën"
            help: "Bekijk, wijzig, verwijder en creëer categoriën."

            list:
              fields:
                - id
                - {property: "name", label: "Naam"}
                - {property: "description", type: "raw", label: "Omschrijving"}
                - {property: "img", type: "image", base_path: "%uploads_categories_path%", label: "Afbeelding"}
                - {property: "product", label: "Producten"}

            form:
              title: "Categorie toevoegen"
              help:

              fields:
                - {type: "group", label: "Informatie", css_class: "col-lg-7"}
                - {property: "name", label: "Naam"}
                - {property: "description", type: "text-editor", label: "Omschrijving"}
                - {type: "group", label: "Upload afbeelding", css_class: "col-lg-5", icon: "clip"}
                - {property: "imgFile", type: "vich_image", label: "Afbeelding"}
            show:
              help:
              fields:
#                - {type: "group", label: "Informatie", css_class: "col-lg-7"}
                - {property: "name", label: "Naam"}
                - {property: "description", type: "raw", label: "Omschrijving"}
                - {property: "createdAt", label: "Gecreëerd"}
                - {property: "updatedAt", label: "Geüpdatet"}
#                - {type: "group", label: "Afbeelding", css_class: "col-lg-5"}
                - {property: "img", type: "image", base_path: "%uploads_categories_path%", label: "Afbeelding"}

        Images:
          class: App\Entity\Images
          label: "Afbeeldingen"

          help: "Bekijk en verwijder afbeeldingen."

          disabled_actions: ["edit", "new"]
          list:
            fields:
              - id
              - {property: "image", type: "image", base_path: "%uploads_products_path%", label: "Afbeelding"}
              - {property: "imageAlt", label: "Titel "}
          show:
            help:
            fields:
              - {property: "imageAlt", label: "Name"}
              - {property: "image", type: "image", base_path: "%uploads_products_path%", label: "Afbeelding"}
              - {property: "product", label: "Product"}



        Orders:
          class: App\Entity\Orders
          label: "Bestellingen"

          help: "Bekijk en verwijder bestellingen."
          disabled_actions: ["new","edit", 'delete']
          list:
            fields:
              - id
              - {property: "date", label: "Geplaatst"}
              - {property: "orderDetails", label: "Details"}
              - {property: "user", label: "Gebruiker"}


        User:
            class: App\Entity\User
            label: "Gebruikers"
            disabled_actions: ['new', 'edit', 'delete']

            help: "Bekijk en verwijder gebruikers."
            list:
              fields:
                - id
                - {property: "firstName", label: "Voornaam"}
                - {property: "lastname", label: "Achternaam"}
                - {property: "email", label: "Email", type: "email"}
                - {property: "phone", label: "Telefoon", type: "tel"}
                - {property: "roles", label: "Rol"}

            show:
              help:
              fields:
                - {property: "firstName", label: "Voornaam"}
                - {property: "lastname", label: "Achternaam"}
                - {property: "email", label: "Email", type: "email"}
                - {property: "phone", label: "Telefoon", type: "tel"}
                - {property: "address", label: "Adres"}
                - {property: "postalCode", type_options: {disabled: true}, label: "Stad"}
                - {property: "createdAt", label: "Gecreëerd"}
                - {property: "updatedAt", label: "Geüpdatet"}
        Price:
          class: App\Entity\Price
          label: "Prijzen"
          help: "Bekijk en voeg prijzen toe"
          list:
            fields:
              - id
              - {property: "price", label: "Prijs"}
              - {property: "tax", label: "Btw"}
              - {property: "startDate", label: "Begin datum"}
              - {property: "endDate", label: "Eind datum"}
              - {property: "product", label: "Product"}
          show:
            help:
            fields:
              - {property: "price", label: "Prijs"}
              - {property: "tax", label: "Btw"}
              - {property: "startDate", label: "Begin datum"}
              - {property: "endDate", label: "Eind datum"}
              - {property: "product", label: "Product"}
          form:
            title: "Prijs toevoegen"
            help:

            fields:
              - {property: "price", label: "Prijs"}
              - {property: "tax", label: "Btw"}
              - {property: "startDate", label: "Begin datum"}
              - {property: "endDate", label: "Eind datum"}
              - {property: "product", label: "Product"}
