vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: "https://wdev.be/wdev_maya/eindwerk/images/products"
            upload_destination: '%kernel.project_dir%/../images/products'
        categories:
            uri_prefix: "https://wdev.be/wdev_maya/eindwerk/images/categories"
            upload_destination: '%kernel.project_dir%/../images/categories'
