vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: "%uploads_products_path%"
            upload_destination: '%kernel.project_dir%/public/%uploads_products_path%'
        categories:
            uri_prefix: "%uploads_categories_path%"
            upload_destination: '%kernel.project_dir%/public/%uploads_categories_path%'
