#index:
#    path: /
#    controller: App\Controller\DefaultController::index

abracadabra:
  path:     /api/login_check
  methods:  [POST]

#app_login:
#  path: /login
#  Controller: App\Controller\DefaultController::index
